### ISSUE TITLE
Desafio 2: Não consigo instalar o sqlite3 driver de jeito nenhum com o docker.

### ISSUE THREAD

**Issue by jhortale** [codeedu/maratona2-desafios#1]
Alguém tem alguma idéia de como faço para fazer o SQLite funcionar dentro do Docker?
Parece que o npm nao instala o modulo, mas ele está lá no package.json

Log do Docker quando rodo o `docker-compose up`:
```
> desafio02@0.0.1 typeorm /home/node/app/backend
maratona-desafio-02 | > ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run"
maratona-desafio-02 | 
maratona-desafio-02 | Error during migration run:
maratona-desafio-02 | DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
maratona-desafio-02 |     at new DriverPackageNotInstalledError (/home/node/app/backend/src/error/DriverPackageNotInstalledError.ts:8:9)
maratona-desafio-02 |     at SqliteDriver.loadDependencies (/home/node/app/backend/src/driver/sqlite/SqliteDriver.ts:128:19)
maratona-desafio-02 |     at new SqliteDriver (/home/node/app/backend/src/driver/sqlite/SqliteDriver.ts:46:14)
maratona-desafio-02 |     at DriverFactory.create (/home/node/app/backend/src/driver/DriverFactory.ts:41:24)
maratona-desafio-02 |     at new Connection (/home/node/app/backend/src/connection/Connection.ts:126:43)
maratona-desafio-02 |     at ConnectionManager.create (/home/node/app/backend/src/connection/ConnectionManager.ts:64:28)
maratona-desafio-02 |     at Object.<anonymous> (/home/node/app/backend/src/index.ts:232:35)
maratona-desafio-02 |     at step (/home/node/app/backend/node_modules/tslib/tslib.js:139:27)
maratona-desafio-02 |     at Object.next (/home/node/app/backend/node_modules/tslib/tslib.js:120:57)
maratona-desafio-02 |     at /home/node/app/backend/node_modules/tslib/tslib.js:113:75 {
maratona-desafio-02 |   name: 'DriverPackageNotInstalledError',
maratona-desafio-02 |   message: 'SQLite package has not been found installed. Try to install it: npm install sqlite3 --save'
maratona-desafio-02 | }
maratona-desafio-02 | npm ERR! code ELIFECYCLE
maratona-desafio-02 | npm ERR! errno 1
maratona-desafio-02 | npm ERR! desafio02@0.0.1 typeorm: `ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run"`
maratona-desafio-02 | npm ERR! Exit status 1
maratona-desafio-02 | npm ERR! 
maratona-desafio-02 | npm ERR! Failed at the desafio02@0.0.1 typeorm script.
maratona-desafio-02 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
maratona-desafio-02 | 
maratona-desafio-02 | npm ERR! A complete log of this run can be found in:
maratona-desafio-02 | npm ERR!     /home/node/app/.npm-cache/_logs/2020-05-06T06_31_08_366Z-debug.log
maratona-desafio-02 | 
maratona-desafio-02 | > desafio02@0.0.1 start:prod /home/node/app/backend
maratona-desafio-02 | > node dist/main
```

**Comment by bmnds** [comment]
E se rodar `npm install sqlite3 --save` antes?

**Comment by wdiego** [comment]
Tb tive esse problema e no meu caso o problema era que a versão do Node da minha máquina era diferente da versão do Node da minha imagem. (se mudar a versão do Node da sua máquina, não se esqueça de apagar a pasta node_modules e rodar o npm install novamente)

**Comment by turnes** [comment]
O  erro diz que não tem o pacote SQLite instalado no teu projeto.
```
name: 'DriverPackageNotInstalledError',
maratona-desafio-02 |   message: 'SQLite package has not been found installed. Try to install it: npm install sqlite3 --save'
```

### Solução 1
1. `npm install sqlite3 --save`

### Solução 2
O pacote SQLite requer que o Python esteja instalado no sistema para instalar. Se você estiver usando a imagem **Alpine** pode ser o "problema". A imagem Alpine não vem com o Python instalado. Antes da linha  `RUN npm install`  coloque `RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++`

Vou deixar um exemplo de Dockerfile

```Dockerfile
FROM node:alpine3.11
WORKDIR /usr/src/app
COPY . ./
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install
    
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
```

**Comment by jhortale** [comment]
valeu pessoal! finalmente consegui, deletando o `node_modules` e rodando esses comandos:

```
FROM node:12.14.1-alpine3.11
RUN apk add --update python make g++\
&& rm -rf /var/cache/apk/*
RUN mkdir /app
WORKDIR /app
COPY package.json /app
RUN npm install --build-from-source
COPY . /app
EXPOSE 3000
```

**Comment by jhortale** [comment]
> E se rodar `npm install sqlite3 --save` antes?

Eu tentei e nao rolou dai tive que usar `RUN npm install --build-from-source`

**Comment by dearrudam** [comment]
@jhortale, tente rodar com a imagem node:14 , pois também enfrentei problemas com isso e depois que eu utilizei a imagem node:14 como base funfou!

``` Dockerfile
FROM node:14

WORKDIR /usr/src/app

COPY . .

RUN npm install && npm run build

EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]
